version: '3'
services:
  movies:
    image: vinodvanama/projectmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: vinodvanama/projecttrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: vinodvanama/projectdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: vinodvanama/projectrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
