version: '3.8'
services:
  movies:
    image: abduljavvadkhan786/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: abduljavvadkhan786/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: abduljavvadkhan786/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: abduljavvadkhan786/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
